#!/bin/bash
#
# setup-sudoers.sh
#
# Lets the GardenPi service user restart the gardenpi-* services (what the
# web UI needs), control them from the command line (start / stop / restart /
# enable / disable), and, unless --no-power is given, reboot / shut down the
# Pi -- all without a password -- by writing /etc/sudoers.d/gardenpi.
#
# Shutdown: the web UI runs scripts/pijuice-safe-shutdown.py as the
# service user (NOT as root -- the script lives under /opt/gardenpi, which
# that user owns and could edit). The script arms the PiJuice and then runs
# `sudo shutdown -h now`, so that exact command line is what's granted
# here. `systemctl poweroff` is not granted: shutting down without the
# PiJuice step means the Pi never powers back on after an outage.
#
# Usage:
#   sudo ./setup-sudoers.sh               # garden.json's application_user, services + reboot/shutdown
#   sudo ./setup-sudoers.sh --no-power    # services only
#   sudo ./setup-sudoers.sh --no-control  # web UI needs only: no command-line
#                                         # start/stop/enable/disable
#   sudo ./setup-sudoers.sh --user bob    # a different service user
#   sudo ./setup-sudoers.sh --remove      # delete /etc/sudoers.d/gardenpi
#
# Safe to re-run: the file is rebuilt from scratch every time.
#
# Only these EXACT command lines are allowed -- no wildcards. (In sudoers a
# `*` in the arguments also matches spaces, so "restart gardenpi-*" would
# let the caller tack any other unit onto the command.) The list and the
# "restart all" argument order must match webui/server/systemControl.js;
# if you add a gardenpi-* service, add it in both places.
#
# Command-line control, for troubleshooting -- one service per command,
# with or without the .service suffix:
#   sudo systemctl stop|start|restart gardenpi-adc
#   sudo systemctl disable|enable [--now] gardenpi-adc   (--now also before/after)
# `stop` alone doesn't keep a service down: it starts again at the next boot
# or when the web UI restarts it. `disable --now` stops it and keeps it
# stopped across reboots (the units don't Want= each other, so nothing else
# pulls it back up); `enable --now` undoes that. The web UI still has no
# Stop button and never issues any of these except restart.
#
# v1.4 2026/09/25 - command-line start, restart without .service, and
#   enable/disable [--now] alongside stop (--no-control leaves them all out;
#   --no-stop is kept as an alias)
# v1.3 2026/09/25 - grant `systemctl stop` for each gardenpi-* service, with
#   and without the .service suffix, for command-line troubleshooting
#   (--no-stop to leave it out)
# v1.2 2026/09/25 - default user is garden.json's config.application_user
#   (via gardenpi-env.sh) instead of a hard-coded pi
# v1.1 2026/09/23 - shutdown goes through pijuice-safe-shutdown.py: grant
#   `shutdown -h now` (what that script runs) instead of `systemctl poweroff`
# v1.0 2026/09/23 - initial version

set -euo pipefail

. "$(dirname "$(readlink -f "$0")")/gardenpi-env.sh"
RUN_AS_USER="$GARDENPI_USER"   # --user overrides
ALLOW_POWER=1
ALLOW_CONTROL=1
REMOVE=0
SUDOERS_FILE="/etc/sudoers.d/gardenpi"

while [ $# -gt 0 ]; do
  case "$1" in
    --user) RUN_AS_USER="${2:?--user needs a name}"; shift 2 ;;
    --no-power) ALLOW_POWER=0; shift ;;
    --no-control|--no-stop) ALLOW_CONTROL=0; shift ;;
    --remove) REMOVE=1; shift ;;
    -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1 (see --help)" >&2; exit 1 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "This script needs to run as root. Try: sudo $0 $*" >&2
  exit 1
fi

if [ "$REMOVE" -eq 1 ]; then
  rm -f "$SUDOERS_FILE"
  echo "Removed $SUDOERS_FILE"
  exit 0
fi

if ! id "$RUN_AS_USER" >/dev/null 2>&1; then
  echo "User '$RUN_AS_USER' does not exist." >&2
  exit 1
fi

# Same resolution rule as systemControl.js, so the path in sudoers is the
# path the web UI actually executes.
if [ -x /usr/bin/systemctl ]; then
  SYSTEMCTL=/usr/bin/systemctl
elif [ -x /bin/systemctl ]; then
  SYSTEMCTL=/bin/systemctl
else
  echo "systemctl not found." >&2
  exit 1
fi

# shutdown binary, same rule as systemControl.js. The script calls a bare
# `sudo shutdown -h now`; sudo resolves it through secure_path, which on
# Debian / Raspberry Pi OS finds /usr/sbin before /sbin.
if [ -x /usr/sbin/shutdown ]; then
  SHUTDOWN=/usr/sbin/shutdown
elif [ -x /sbin/shutdown ]; then
  SHUTDOWN=/sbin/shutdown
else
  echo "shutdown not found." >&2
  exit 1
fi

# Startup order (matches add-services.sh). gardenpi-init is restartable on
# its own but is not part of "restart all".
ALL_SERVICES="gardenpi-init gardenpi-leds gardenpi-adc gardenpi-irrigation gardenpi-weather gardenpi-api gardenpi-webui"
RESTART_ALL_SERVICES="gardenpi-leds gardenpi-adc gardenpi-irrigation gardenpi-weather gardenpi-api gardenpi-webui"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# /etc/sudoers.d/gardenpi -- generated by $(basename "$0") on $(date -Iseconds)"
  echo "# Lets the GardenPi service user ($RUN_AS_USER) restart GardenPi services"
  [ "$ALLOW_CONTROL" -eq 1 ] && echo "# and start/stop/enable/disable them from the command line (troubleshooting),"
  [ "$ALLOW_POWER" -eq 1 ] && echo "# and reboot / shut down the system (shutdown via pijuice-safe-shutdown.py)."
  echo "# Re-run setup-sudoers.sh to regenerate; do not edit by hand."
  echo
  printf 'Cmnd_Alias GARDENPI_RESTART = \\\n'
  first=1
  for svc in $ALL_SERVICES; do
    [ $first -eq 1 ] || printf ', \\\n'
    printf '    %s restart %s.service' "$SYSTEMCTL" "$svc"
    first=0
  done
  printf ', \\\n    %s restart' "$SYSTEMCTL"
  for svc in $RESTART_ALL_SERVICES; do printf ' %s.service' "$svc"; done
  printf '\n\n'
  aliases="GARDENPI_RESTART"
  if [ "$ALLOW_CONTROL" -eq 1 ]; then
    # Every service, with and without ".service", one unit per command:
    #   start / stop / restart NAME
    #   enable / disable NAME, NAME --now, --now NAME
    # (restart NAME.service is already in GARDENPI_RESTART above.)
    printf 'Cmnd_Alias GARDENPI_CONTROL = \\\n'
    first=1
    emit() { [ $first -eq 1 ] || printf ', \\\n'; printf '    %s %s' "$SYSTEMCTL" "$1"; first=0; }
    for svc in $ALL_SERVICES; do
      for name in "$svc" "$svc.service"; do
        emit "start $name"
        emit "stop $name"
        [ "$name" = "$svc" ] && emit "restart $name"
        for verb in enable disable; do
          emit "$verb $name"
          emit "$verb $name --now"
          emit "$verb --now $name"
        done
      done
    done
    printf '\n\n'
    aliases="$aliases, GARDENPI_CONTROL"
  fi
  if [ "$ALLOW_POWER" -eq 1 ]; then
    echo "Cmnd_Alias GARDENPI_POWER = $SYSTEMCTL reboot, $SHUTDOWN -h now"
    echo
    aliases="$aliases, GARDENPI_POWER"
  fi
  echo "$RUN_AS_USER ALL=(root) NOPASSWD: $aliases"
} > "$TMP"

# Never install a file visudo rejects -- a broken sudoers.d file can lock
# sudo out for every user on the box.
if ! visudo -cf "$TMP" >/dev/null; then
  echo "Generated sudoers file failed validation; nothing was installed:" >&2
  visudo -cf "$TMP" >&2 || true
  exit 1
fi

install -m 0440 -o root -g root "$TMP" "$SUDOERS_FILE"
echo "Installed $SUDOERS_FILE:"
echo
cat "$SUDOERS_FILE"
echo
echo "Check with: sudo -u $RUN_AS_USER sudo -n -l $SYSTEMCTL restart gardenpi-leds.service"
