#!/bin/bash
#
# setup-sudoers.sh
#
# Lets the GardenPi web UI restart the gardenpi-* services (and, unless
# --no-power is given, reboot / shut down the Pi) without a password, by
# writing /etc/sudoers.d/gardenpi.
#
# Shutdown: the web UI runs scripts/pijuice-safe-shutdown.py as the
# service user (NOT as root -- the script lives under /opt/gardenpi, which
# that user owns and could edit). The script arms the PiJuice and then runs
# `sudo shutdown -h now`, so that exact command line is what's granted
# here. `systemctl poweroff` is not granted: shutting down without the
# PiJuice step means the Pi never powers back on after an outage.
#
# Usage:
#   sudo ./setup-sudoers.sh               # user "pi", services + reboot/poweroff
#   sudo ./setup-sudoers.sh --no-power    # services only
#   sudo ./setup-sudoers.sh --user bob    # a different service user
#   sudo ./setup-sudoers.sh --remove      # delete /etc/sudoers.d/gardenpi
#
# Safe to re-run: the file is rebuilt from scratch every time.
#
# Only these EXACT command lines are allowed -- no wildcards. (In sudoers a
# `*` in the arguments also matches spaces, so "restart gardenpi-*" would
# let the caller tack any other unit onto the command.) The list and the
# "restart all" argument order must match webui/server/systemControl.js;
# if you add a gardenpi-* service, add it in both places.
#
# Stop is deliberately not granted: a stopped gardenpi-webui can only be
# restarted from an ssh session.
#
# v1.1 2026/09/23 - shutdown goes through pijuice-safe-shutdown.py: grant
#   `shutdown -h now` (what that script runs) instead of `systemctl poweroff`
# v1.0 2026/09/23 - initial version

set -euo pipefail

RUN_AS_USER="pi"
ALLOW_POWER=1
REMOVE=0
SUDOERS_FILE="/etc/sudoers.d/gardenpi"

while [ $# -gt 0 ]; do
  case "$1" in
    --user) RUN_AS_USER="${2:?--user needs a name}"; shift 2 ;;
    --no-power) ALLOW_POWER=0; shift ;;
    --remove) REMOVE=1; shift ;;
    -h|--help) sed -n '2,24p' "$0"; exit 0 ;;
    *) echo "Unknown option: $1 (see --help)" >&2; exit 1 ;;
  esac
done

if [ "$(id -u)" -ne 0 ]; then
  echo "This script needs to run as root. Try: sudo $0 $*" >&2
  exit 1
fi

if [ "$REMOVE" -eq 1 ]; then
  rm -f "$SUDOERS_FILE"
  echo "Removed $SUDOERS_FILE"
  exit 0
fi

if ! id "$RUN_AS_USER" >/dev/null 2>&1; then
  echo "User '$RUN_AS_USER' does not exist." >&2
  exit 1
fi

# Same resolution rule as systemControl.js, so the path in sudoers is the
# path the web UI actually executes.
if [ -x /usr/bin/systemctl ]; then
  SYSTEMCTL=/usr/bin/systemctl
elif [ -x /bin/systemctl ]; then
  SYSTEMCTL=/bin/systemctl
else
  echo "systemctl not found." >&2
  exit 1
fi

# shutdown binary, same rule as systemControl.js. The script calls a bare
# `sudo shutdown -h now`; sudo resolves it through secure_path, which on
# Debian / Raspberry Pi OS finds /usr/sbin before /sbin.
if [ -x /usr/sbin/shutdown ]; then
  SHUTDOWN=/usr/sbin/shutdown
elif [ -x /sbin/shutdown ]; then
  SHUTDOWN=/sbin/shutdown
else
  echo "shutdown not found." >&2
  exit 1
fi

# Startup order (matches add-services.sh). gardenpi-init is restartable on
# its own but is not part of "restart all".
ALL_SERVICES="gardenpi-init gardenpi-leds gardenpi-adc gardenpi-irrigation gardenpi-weather gardenpi-api gardenpi-webui"
RESTART_ALL_SERVICES="gardenpi-leds gardenpi-adc gardenpi-irrigation gardenpi-weather gardenpi-api gardenpi-webui"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# /etc/sudoers.d/gardenpi -- generated by $(basename "$0") on $(date -Iseconds)"
  echo "# Lets the GardenPi web UI (user: $RUN_AS_USER) restart GardenPi services"
  [ "$ALLOW_POWER" -eq 1 ] && echo "# and reboot / shut down the system (shutdown via pijuice-safe-shutdown.py)."
  echo "# Re-run setup-sudoers.sh to regenerate; do not edit by hand."
  echo
  printf 'Cmnd_Alias GARDENPI_RESTART = \\\n'
  first=1
  for svc in $ALL_SERVICES; do
    [ $first -eq 1 ] || printf ', \\\n'
    printf '    %s restart %s.service' "$SYSTEMCTL" "$svc"
    first=0
  done
  printf ', \\\n    %s restart' "$SYSTEMCTL"
  for svc in $RESTART_ALL_SERVICES; do printf ' %s.service' "$svc"; done
  printf '\n\n'
  if [ "$ALLOW_POWER" -eq 1 ]; then
    echo "Cmnd_Alias GARDENPI_POWER = $SYSTEMCTL reboot, $SHUTDOWN -h now"
    echo
    echo "$RUN_AS_USER ALL=(root) NOPASSWD: GARDENPI_RESTART, GARDENPI_POWER"
  else
    echo "$RUN_AS_USER ALL=(root) NOPASSWD: GARDENPI_RESTART"
  fi
} > "$TMP"

# Never install a file visudo rejects -- a broken sudoers.d file can lock
# sudo out for every user on the box.
if ! visudo -cf "$TMP" >/dev/null; then
  echo "Generated sudoers file failed validation; nothing was installed:" >&2
  visudo -cf "$TMP" >&2 || true
  exit 1
fi

install -m 0440 -o root -g root "$TMP" "$SUDOERS_FILE"
echo "Installed $SUDOERS_FILE:"
echo
cat "$SUDOERS_FILE"
echo
echo "Check with: sudo -u $RUN_AS_USER sudo -n -l $SYSTEMCTL restart gardenpi-leds.service"
